"""Claude Code install helpers."""

from __future__ import annotations

import argparse
from pathlib import Path

from multi_agent_brief.install.writer import (
    InstallWriteError,
    PlannedWrite,
    apply_planned_writes,
)


INSTALL_MARKER = "<!-- Generated by multi-agent-brief claude install. -->"


def register(subparsers: argparse._SubParsersAction) -> None:
    claude_parser = subparsers.add_parser(
        "claude",
        help="Install or inspect Claude Code assets for MABW.",
    )
    actions = claude_parser.add_subparsers(dest="claude_action", required=True)

    install = actions.add_parser(
        "install",
        help="Install /briefloop, /mabw, /generate-brief, and MABW subagents into ~/.claude.",
    )
    install.add_argument(
        "--repo-workdir",
        default=".",
        help="MABW source repository root (default: current directory).",
    )
    install.add_argument(
        "--target",
        default=str(Path.home() / ".claude"),
        help="Claude Code user config directory (default: ~/.claude).",
    )
    install.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing non-MABW files in target locations.",
    )
    install.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned writes without changing files.",
    )


def handle(args: argparse.Namespace) -> int:
    if args.claude_action == "install":
        try:
            return _install(args)
        except RuntimeError as exc:
            print(f"[claude install] {exc}")
            return 1
    return 1


def _install(args: argparse.Namespace) -> int:
    repo = Path(args.repo_workdir).expanduser().resolve()
    target = Path(args.target).expanduser().resolve()
    command_dir = repo / ".claude" / "commands"
    generate_src = command_dir / "generate-brief.md"
    briefloop_src = command_dir / "briefloop.md"
    mabw_src = command_dir / "mabw.md"
    agents_src = repo / ".claude" / "agents"
    if not generate_src.exists():
        raise RuntimeError(f"Claude command not found: {generate_src}")
    if not briefloop_src.exists():
        raise RuntimeError(f"Claude command not found: {briefloop_src}")
    if not mabw_src.exists():
        raise RuntimeError(f"Claude command not found: {mabw_src}")
    if not agents_src.exists():
        raise RuntimeError(f"Claude agents directory not found: {agents_src}")

    agents_dst = target / "agents" / "mabw"

    command_sources = [briefloop_src, mabw_src, generate_src]
    writes: list[PlannedWrite] = [
        PlannedWrite(
            target / "commands" / src.name,
            _installed_command_text(src, repo=repo),
        )
        for src in command_sources
    ]
    for src in sorted(agents_src.glob("*.md")):
        writes.append(PlannedWrite(agents_dst / src.name, _installed_agent_text(src)))

    try:
        planned = apply_planned_writes(
            writes=writes,
            root=target,
            force=bool(args.force),
            dry_run=bool(args.dry_run),
            generated_markers=(INSTALL_MARKER,),
        )
    except InstallWriteError as exc:
        raise RuntimeError(str(exc)) from exc

    if args.dry_run:
        for dst in planned:
            print(f"[claude install] would write {dst}")
        return 0

    for dst in planned:
        print(f"[claude install] wrote {dst}")

    print("")
    print("[claude install] Installed /briefloop, /mabw, and /generate-brief for Claude Code CLI and Claude Desktop Code tab.")
    print("[claude install] In Claude Code, type '/' and confirm /briefloop or /mabw is listed.")
    return 0


def _installed_command_text(command_src: Path, *, repo: Path) -> str:
    text = command_src.read_text(encoding="utf-8")
    if command_src.name != "generate-brief.md":
        return _with_install_marker(text)

    repo_text = repo.as_posix()
    text = text.replace(
        "Read shared contract references before delegation:\n\n"
        "- `configs/orchestrator_contract.yaml`\n"
        "- `configs/stage_specs.yaml`\n"
        "- `configs/artifact_contracts.yaml`\n"
        "- `configs/policy_packs/default.yaml`",
        "This command was installed from the MABW source repository:\n\n"
        f"- `{repo_text}`\n\n"
        "Read shared contract references before delegation:\n\n"
        f"- `{repo_text}/configs/orchestrator_contract.yaml`\n"
        f"- `{repo_text}/configs/stage_specs.yaml`\n"
        f"- `{repo_text}/configs/artifact_contracts.yaml`\n"
        f"- `{repo_text}/configs/policy_packs/default.yaml`",
    )
    text = text.replace(
        "You are the Orchestrator main agent generating a real user-facing brief for workspace: $ARGUMENTS.",
        "You are the Orchestrator main agent generating a real user-facing brief for workspace: $ARGUMENTS.\n\n"
        "If $ARGUMENTS is a relative path, resolve it from the current Claude Code project folder. "
        "If the workspace is not found, ask for an absolute workspace path before proceeding.",
    )
    return _with_install_marker(text)


def _installed_agent_text(agent_src: Path) -> str:
    return _with_install_marker(agent_src.read_text(encoding="utf-8"))


def _with_install_marker(text: str) -> str:
    """Insert the marker without breaking Markdown YAML frontmatter."""
    if text.startswith("---\n"):
        close = text.find("\n---", 4)
        if close != -1:
            close_end = close + len("\n---")
            if close_end < len(text) and text[close_end] == "\n":
                close_end += 1
            return f"{text[:close_end]}{INSTALL_MARKER}\n{text[close_end:]}"
    return f"{INSTALL_MARKER}\n{text}"
