"""Materialize durable source evidence records into workspace source packs."""

from __future__ import annotations

import hashlib
import json
from dataclasses import replace
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from multi_agent_brief.contracts.source_metadata import (
    normalize_retrieval_source_type,
    normalize_source_category,
    normalize_underlying_evidence_type,
)
from multi_agent_brief.sources.base import SourceItem, SourceQuery
from multi_agent_brief.sources.registry import collect_all_sources, load_sources_config

SOURCE_EVIDENCE_RECORD_SCHEMA = "mabw.source_evidence_record.v1"
SOURCE_EVIDENCE_PACK_MANIFEST_SCHEMA = "mabw.source_evidence_pack_manifest.v1"
DURABLE_MATERIALIZATION_PROVIDERS = {"manual", "cached_package"}
SOURCE_EXCERPT_LIMIT = 2000


class SourceEvidencePackError(Exception):
    """Raised when source evidence pack materialization cannot proceed."""


def materialize_source_evidence_pack(
    *,
    config_path: str | Path,
    force: bool = False,
) -> dict[str, Any]:
    config_file = Path(config_path).expanduser().resolve()
    workspace = config_file.parent
    sources_path = workspace / "sources.yaml"
    if not config_file.exists():
        raise SourceEvidencePackError(f"config.yaml not found: {config_file}")
    if not sources_path.exists():
        raise SourceEvidencePackError(f"sources.yaml not found: {sources_path}")

    source_config = load_sources_config(sources_path)
    durable_provider_names = [
        name for name in source_config.enabled_providers if name in DURABLE_MATERIALIZATION_PROVIDERS
    ]
    if not durable_provider_names:
        raise SourceEvidencePackError(
            "No durable source materialization providers are enabled. "
            "Enable manual or cached_package sources; do not materialize source_candidates.yaml."
        )

    durable_config = replace(source_config, enabled_providers=durable_provider_names)
    items, provider_errors = collect_all_sources(
        durable_config,
        SourceQuery(recency_days=0),
        parallel=False,
    )
    if provider_errors:
        raise SourceEvidencePackError(
            "Durable source materialization provider errors must be resolved before writing a pack: "
            + _format_provider_errors(provider_errors)
        )
    if not items:
        raise SourceEvidencePackError("No durable source records were collected.")

    source_dir = workspace / "input" / "sources"
    intermediate_dir = workspace / "output" / "intermediate"
    planned = _plan_source_records(items, workspace=workspace, source_dir=source_dir)
    duplicate_source_ids = _duplicate_source_ids(planned)
    if duplicate_source_ids:
        raise SourceEvidencePackError(
            "Source evidence pack contains duplicate source_id values; "
            "make source IDs unique before materialization: "
            + ", ".join(duplicate_source_ids)
        )
    existing = [
        _workspace_relative(workspace, entry["target"])
        for entry in planned
        if entry["target"].exists()
    ]
    if existing:
        if force:
            unsafe = [
                path
                for path in existing
                if not _is_generated_source_evidence_record(workspace / path)
            ]
            if unsafe:
                raise SourceEvidencePackError(
                    "--force can only replace records generated by sources.materialize-pack; "
                    "refusing to overwrite: " + ", ".join(unsafe)
                )
        else:
            raise SourceEvidencePackError(
                "Source evidence pack targets already exist; rerun with --force to replace generated records: "
                + ", ".join(existing)
            )

    source_dir.mkdir(parents=True, exist_ok=True)
    intermediate_dir.mkdir(parents=True, exist_ok=True)

    records: list[dict[str, Any]] = []
    for entry in planned:
        target = entry["target"]
        payload = entry["payload"]
        target.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        records.append({
            "source_id": payload["source_id"],
            "path": _workspace_relative(workspace, target),
            "sha256": _sha256_file(target),
            "size_bytes": target.stat().st_size,
            "source_url": payload.get("source_url", ""),
            "source_title": payload.get("source_title", ""),
            "publisher": payload.get("publisher", ""),
            "source_type": payload.get("source_type", ""),
            "source_category": payload.get("source_category", ""),
            "retrieval_source_type": payload.get("retrieval_source_type", ""),
            "underlying_evidence_type": payload.get("underlying_evidence_type", ""),
            "raw_underlying_evidence_type": payload.get("raw_underlying_evidence_type", ""),
        })

    manifest = {
        "schema_version": SOURCE_EVIDENCE_PACK_MANIFEST_SCHEMA,
        "source": "sources.materialize-pack",
        "source_config_path": _workspace_relative(workspace, sources_path),
        "durable_provider_names": durable_provider_names,
        "record_count": len(records),
        "error_count": len(provider_errors),
        "records": records,
        "provider_errors": provider_errors,
        "pack_sha256": _sha256_json([
            {
                "path": record["path"],
                "sha256": record["sha256"],
                "size_bytes": record["size_bytes"],
                "source_id": record["source_id"],
            }
            for record in records
        ]),
        "non_goals": [
            "semantic_support_assessment",
            "claim_support_matrix_generation",
            "source_candidates_as_evidence",
            "automatic_delivery_approval",
        ],
    }
    manifest_path = intermediate_dir / "source_evidence_pack_manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return {
        "ok": True,
        "workspace": str(workspace),
        "manifest_path": _workspace_relative(workspace, manifest_path),
        "record_count": len(records),
        "error_count": len(provider_errors),
        "records": records,
        "provider_errors": provider_errors,
        "pack_sha256": manifest["pack_sha256"],
    }


def _is_generated_source_evidence_record(path: Path) -> bool:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return False
    return (
        isinstance(payload, dict)
        and payload.get("schema_version") == SOURCE_EVIDENCE_RECORD_SCHEMA
        and payload.get("source") == "sources.materialize-pack"
    )


def _format_provider_errors(provider_errors: list[dict[str, str]]) -> str:
    formatted: list[str] = []
    for error in provider_errors:
        provider = str(error.get("provider") or "unknown").strip() or "unknown"
        error_type = str(error.get("error_type") or "error").strip() or "error"
        message = str(error.get("message") or "").strip()
        formatted.append(f"{provider}:{error_type}" + (f":{message}" if message else ""))
    return "; ".join(formatted)


def _plan_source_records(
    items: list[SourceItem],
    *,
    workspace: Path,
    source_dir: Path,
) -> list[dict[str, Any]]:
    planned: list[dict[str, Any]] = []
    used_names: set[str] = set()
    for item in items:
        payload = _source_item_payload(item)
        filename = _unique_record_filename(item, payload, used_names)
        target = source_dir / filename
        payload["source_path"] = _workspace_relative(workspace, target)
        payload["source_bytes_path"] = payload["source_path"]
        planned.append({"payload": payload, "target": target})
    return planned


def _duplicate_source_ids(planned: list[dict[str, Any]]) -> list[str]:
    seen: set[str] = set()
    duplicates: set[str] = set()
    for entry in planned:
        payload = entry.get("payload")
        if not isinstance(payload, dict):
            continue
        source_id = str(payload.get("source_id") or "").strip()
        if not source_id:
            continue
        if source_id in seen:
            duplicates.add(source_id)
        seen.add(source_id)
    return sorted(duplicates)


def _source_item_payload(item: SourceItem) -> dict[str, Any]:
    metadata = item.metadata if isinstance(item.metadata, dict) else {}
    content = item.content.strip()
    content_sha = hashlib.sha256(content.encode("utf-8")).hexdigest()
    source_url = item.url.strip()
    source_title = item.title.strip() or item.source_name.strip() or item.source_id.strip()
    source_name = item.source_name.strip() or item.source_id.strip()
    publisher = _first_text(
        metadata,
        "publisher_or_institution",
        "publisher",
        "institution",
        "source_name",
    ) or source_name
    raw_underlying_evidence_type = _first_text(
        metadata,
        "underlying_evidence_type",
        "source_category",
        "evidence_category",
        "category",
    ) or "unknown"
    raw_retrieval_source_type = _first_text(
        metadata,
        "retrieval_source_type",
        "provider_type",
        "storage_type",
    )
    provider_source_type = _provider_source_type(item.source_type)
    retrieval_source_type = _normalize_pack_retrieval_source_type(
        raw_retrieval_source_type=raw_retrieval_source_type,
        provider_source_type=provider_source_type,
        raw_underlying_evidence_type=raw_underlying_evidence_type,
    )
    underlying_evidence_type = normalize_underlying_evidence_type(raw_underlying_evidence_type)
    source_category = normalize_source_category(underlying_evidence_type, raw_underlying_evidence_type)
    return {
        "schema_version": SOURCE_EVIDENCE_RECORD_SCHEMA,
        "source": "sources.materialize-pack",
        "source_id": item.source_id.strip(),
        "source_url": source_url,
        "source_title": source_title,
        "source_name": source_name,
        "publisher": publisher,
        "publisher_or_institution": publisher,
        "published_at": item.published_at.strip(),
        "retrieved_at": item.retrieved_at.strip() or _utc_now_iso(),
        "source_type": provider_source_type,
        "retrieval_source_type": retrieval_source_type,
        "source_category": source_category,
        "evidence_category": source_category,
        "underlying_evidence_type": underlying_evidence_type,
        "raw_underlying_evidence_type": raw_underlying_evidence_type,
        "raw_excerpt": content[:SOURCE_EXCERPT_LIMIT],
        "content": content,
        "sha256": content_sha,
        "metadata": {
            "language": item.language.strip(),
            "reliability": item.reliability.strip(),
            "dedupe_key": item.dedupe_key.strip(),
        },
    }


def _unique_record_filename(item: SourceItem, payload: dict[str, Any], used_names: set[str]) -> str:
    base = _slug(item.source_id) or _slug(payload.get("source_title")) or "source"
    digest = hashlib.sha256(
        json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()[:10]
    candidate = f"{base}.json"
    if candidate in used_names:
        candidate = f"{base}-{digest}.json"
    while candidate in used_names:
        digest = hashlib.sha256(candidate.encode("utf-8")).hexdigest()[:10]
        candidate = f"{base}-{digest}.json"
    used_names.add(candidate)
    return candidate


def _slug(value: Any) -> str:
    raw = str(value or "").strip().lower()
    slug = "".join(ch if ("a" <= ch <= "z" or "0" <= ch <= "9") else "-" for ch in raw).strip("-")
    return slug[:64]


def _first_text(metadata: dict[str, Any], *keys: str) -> str:
    for key in keys:
        value = metadata.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


def _provider_source_type(value: str) -> str:
    normalized = str(value or "").strip()
    if normalized == "cached":
        return "cached_package"
    return normalized or "local_file"


def _normalize_pack_retrieval_source_type(
    *,
    raw_retrieval_source_type: str,
    provider_source_type: str,
    raw_underlying_evidence_type: str,
) -> str:
    if provider_source_type == "cached_package":
        return normalize_retrieval_source_type(
            raw_retrieval_source_type,
            raw_underlying_evidence_type,
            provider_source_type,
        )
    return normalize_retrieval_source_type(
        raw_retrieval_source_type,
        provider_source_type,
        raw_underlying_evidence_type,
    )


def _workspace_relative(workspace: Path, path: Path) -> str:
    return path.resolve().relative_to(workspace.resolve()).as_posix()


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _sha256_json(payload: Any) -> str:
    raw = json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()
