from __future__ import annotations

import re

from multi_agent_brief.audit.deterministic import SRC_REF_PATTERN
from multi_agent_brief.audit.interfaces import AuditAgentInterface
from multi_agent_brief.core.claim_ledger import ClaimLedger
from multi_agent_brief.core.schemas import AuditFinding, AuditReport, PipelineContext


QUALITY_RULES: list[tuple[str, str, str, str]] = [
    (
        r"\bTBD\b|to be completed|待(?:完整文本)?(?:提取|补充)",
        "placeholder_text",
        "Draft contains placeholder text.",
        "Replace placeholders with sourced content or remove the item.",
    ),
    (
        r"\b(?:Ledger|raw_text|Scout|Packet)\b|CAP类条目|T5级",
        "internal_process_term",
        "Draft contains internal workflow terminology.",
        "Rewrite internal workflow language as reader-facing source context.",
    ),
    (
        r"Step\s*[0-9]",
        "step_label_residue",
        "Draft contains step labels that look like process residue.",
        "Remove process labels before publication.",
    ),
    (
        r"(?:audit status|generated by|编制说明|审计状态|生成工具)\s*[：:]",
        "compilation_residue",
        "Draft contains audit or generation metadata residue.",
        "Remove generation metadata from the reader-facing brief.",
    ),
    (
        r"全面落地(?!.*\d{4}-\d{2}-\d{2})|最终规则明确(?!.*\d{4}-\d{2}-\d{2})|first invoked|首次动用",
        "unsupported_certainty",
        "Draft uses high-certainty policy wording without a date or sufficient support.",
        "Add precise source/date support or weaken the claim.",
    ),
    (
        r"\b(buy|sell|strong buy|price target|trading signal)\b|买入评级|卖出评级|目标价|交易信号",
        "investment_advice_language",
        "Draft contains investment-advice style language.",
        "Keep the brief analytical and non-advisory.",
    ),
]

NUMBER_PATTERN = re.compile(r"(?<!\[src:)(?<!\[)(?<!\w)(\$[\d,.]+|[\d.]+%(?!\w)|[\d.]+ ?(?:GW|GWh|MW|MWh|bps))")


class QualityHarnessAuditAgent(AuditAgentInterface):
    """Generic quality harness ported from local workflow prototypes."""

    name = "quality-harness-auditor"

    def run_audit(
        self,
        markdown: str,
        ledger: ClaimLedger,
        context: PipelineContext | None = None,
    ) -> AuditReport:
        findings: list[AuditFinding] = []
        findings.extend(_empty_report_findings(markdown, ledger, context))
        findings.extend(_regex_rule_findings(markdown))
        findings.extend(_claim_gate_findings(markdown, ledger))
        findings.extend(_source_density_findings(markdown))
        findings.extend(_unit_guard_findings(markdown))
        findings.extend(_repeat_summary_findings(markdown, ledger))
        findings.extend(_stale_filler_findings(markdown))
        return AuditReport(audit_status="pass", audit_score=100, findings=findings)


def _empty_report_findings(
    markdown: str,
    ledger: ClaimLedger,
    context: PipelineContext | None,
) -> list[AuditFinding]:
    selection = context.metadata.get("selection", {}) if context else {}
    quiet_week = bool(selection.get("quiet_week")) if selection else False
    if len(ledger) > 0:
        return []
    if quiet_week and context and context.metadata.get("allow_empty_quiet_week") is True:
        return []
    if "No candidate claims were found." not in markdown and markdown.strip():
        return []
    return [
        AuditFinding(
            finding_id="EMPTY_001",
            severity="high",
            finding_type="no_reportable_claims",
            description="Pipeline produced a brief with zero reportable claims.",
            recommendation="Add usable source inputs or explicitly mark this as an allowed empty quiet-week run.",
        )
    ]


def _regex_rule_findings(markdown: str) -> list[AuditFinding]:
    findings: list[AuditFinding] = []
    for pattern, finding_type, description, recommendation in QUALITY_RULES:
        for match in re.finditer(pattern, markdown, re.IGNORECASE | re.MULTILINE):
            findings.append(
                AuditFinding(
                    finding_id=f"HARNESS_{len(findings)+1:03d}",
                    severity="high" if finding_type in {"placeholder_text", "investment_advice_language"} else "medium",
                    finding_type=finding_type,
                    description=description,
                    recommendation=recommendation,
                    evidence=match.group(0),
                )
            )
    return findings


def _claim_gate_findings(markdown: str, ledger: ClaimLedger) -> list[AuditFinding]:
    findings: list[AuditFinding] = []
    referenced_ids = {match.group(1) for match in SRC_REF_PATTERN.finditer(markdown)}
    for claim_id in referenced_ids:
        claim = ledger.get_claim(claim_id)
        if claim is None:
            continue
        claim_type = claim.claim_type
        source_tier = str(claim.metadata.get("source_tier", "") or "")
        if claim_type == "needs_recrawl":
            findings.append(
                AuditFinding(
                    finding_id=f"RECRAWL_{len(findings)+1:03d}",
                    severity="high",
                    finding_type="needs_recrawl_claim_used",
                    related_claim_id=claim_id,
                    description="A needs_recrawl claim is cited in the brief.",
                    recommendation="Remove the claim and recrawl the source before using it.",
                    evidence=claim.statement,
                )
            )
        if source_tier == "T5":
            findings.append(
                AuditFinding(
                    finding_id=f"TIER_{len(findings)+1:03d}",
                    severity="high",
                    finding_type="low_confidence_source_used",
                    related_claim_id=claim_id,
                    description="A T5 or low-confidence source is cited in the brief.",
                    recommendation="Replace it with a higher-tier source or remove the item.",
                    evidence=claim.statement,
                )
            )
    return findings


def _source_density_findings(markdown: str) -> list[AuditFinding]:
    numbers = NUMBER_PATTERN.findall(markdown)
    refs = SRC_REF_PATTERN.findall(markdown)
    if numbers and len(refs) < len(numbers) * 0.5:
        return [
            AuditFinding(
                finding_id="DENSITY_001",
                severity="high",
                finding_type="low_source_density",
                description=f"Many number-like values lack source coverage: {len(numbers)} numbers, {len(refs)} source references.",
                recommendation="Attach source references to key numbers or remove unsupported figures.",
                evidence=", ".join(numbers[:10]),
            )
        ]
    return []


def _unit_guard_findings(markdown: str) -> list[AuditFinding]:
    findings: list[AuditFinding] = []
    for match in re.finditer(r"([0-9][0-9,]*(?:\.[0-9]+)?)\s*(?:千兆瓦时|GWh).{0,100}\[src:EIA_GEN_", markdown):
        value = float(match.group(1).replace(",", ""))
        if value > 1000:
            findings.append(
                AuditFinding(
                    finding_id=f"UNIT_{len(findings)+1:03d}",
                    severity="high",
                    finding_type="possible_eia_unit_inflation",
                    description="EIA generation value may have been inflated from thousand MWh into GWh.",
                    recommendation="Check whether the source unit is thousand MWh; write the equivalent GWh correctly.",
                    evidence=match.group(0),
                )
            )
    return findings


def _repeat_summary_findings(markdown: str, ledger: ClaimLedger) -> list[AuditFinding]:
    summary = _section_between(markdown, "## Executive Summary", "\n## ")
    if not summary:
        return []
    findings: list[AuditFinding] = []
    for match in SRC_REF_PATTERN.finditer(summary):
        claim = ledger.get_claim(match.group(1))
        if claim and claim.metadata.get("repeat") is True:
            findings.append(
                AuditFinding(
                    finding_id=f"REPEAT_{len(findings)+1:03d}",
                    severity="medium",
                    finding_type="repeat_claim_in_summary",
                    related_claim_id=claim.claim_id,
                    description="A repeated/background claim appears in the executive summary.",
                    recommendation="Keep executive summary focused on fresh report-window changes.",
                    evidence=claim.statement,
                )
            )
    return findings


def _stale_filler_findings(markdown: str) -> list[AuditFinding]:
    hits = re.findall(r"本期无新增|暂无新增|无新增可核验|上期已覆盖|previously covered|no material update", markdown, re.IGNORECASE)
    if len(hits) >= 3:
        return [
            AuditFinding(
                finding_id="FILLER_001",
                severity="medium",
                finding_type="stale_filler_language",
                description=f"Brief contains {len(hits)} stale/no-update filler phrases.",
                recommendation="Remove no-update filler sections unless they carry a specific decision impact.",
                evidence=", ".join(hits[:10]),
            )
        ]
    return []


def _section_between(content: str, start: str, end: str) -> str:
    start_idx = content.find(start)
    if start_idx < 0:
        return ""
    end_idx = content.find(end, start_idx + len(start))
    return content[start_idx:end_idx if end_idx >= 0 else len(content)]
