"""Workspace-local runtime asset installation helpers."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from multi_agent_brief.install.writer import (
    InstallWriteError,
    PlannedWrite,
    apply_planned_writes,
)
from multi_agent_brief.orchestrator_contract import is_source_repo, resolve_repo_workdir


INSTALL_MARKER = "<!-- Generated by multi-agent-brief runtime install. -->"
JSONC_INSTALL_MARKER = "// Generated by multi-agent-brief runtime install."
TOML_INSTALL_MARKER = "# Generated by multi-agent-brief runtime install."
SKILL_NAME = "multi-agent-brief-workflow"
SUPPORTED_RUNTIMES = ("opencode", "claude", "codex")
SOURCE_CLONE_ONLY_MESSAGE = (
    "Runtime workspace kit assets are source-clone-only in this install. "
    "Run this command from a MABW source clone, or pass --repo-workdir pointing "
    "to a source repository that contains .opencode/.claude/.codex/.agents assets."
)


class RuntimeAssetInstallError(RuntimeError):
    """Raised when workspace runtime assets cannot be installed."""


def install_runtime_kit(
    *,
    workspace: str | Path,
    runtime: str,
    repo_workdir: str | Path | None = None,
    force: bool = False,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Install runtime-discoverable assets into a user workspace."""
    ws = Path(workspace).expanduser().resolve()
    if not ws.exists() or not ws.is_dir():
        raise RuntimeAssetInstallError(f"Workspace directory not found: {ws}")

    runtimes = SUPPORTED_RUNTIMES if runtime == "all" else (runtime,)
    unknown = [name for name in runtimes if name not in SUPPORTED_RUNTIMES]
    if unknown:
        raise RuntimeAssetInstallError(f"Unsupported runtime: {', '.join(unknown)}")

    repo = _resolve_source_repo(repo_workdir=repo_workdir, workspace=ws)

    all_writes: list[PlannedWrite] = []
    for runtime_name in runtimes:
        if runtime_name == "opencode":
            all_writes.extend(_opencode_writes(workspace=ws, repo=repo))
        elif runtime_name == "claude":
            all_writes.extend(_claude_writes(workspace=ws, repo=repo))
        elif runtime_name == "codex":
            all_writes.extend(_codex_writes(workspace=ws, repo=repo))
    all_writes = _deduplicate_writes(all_writes)

    try:
        apply_planned_writes(
            writes=all_writes,
            root=ws,
            force=force,
            dry_run=dry_run,
            generated_markers=(INSTALL_MARKER, JSONC_INSTALL_MARKER, TOML_INSTALL_MARKER),
        )
    except InstallWriteError as exc:
        raise RuntimeAssetInstallError(str(exc)) from exc

    return {
        "runtime": runtime,
        "workspace": str(ws),
        "repo_workdir": str(repo),
        "dry_run": dry_run,
        "written": [str(write.destination) for write in all_writes],
        "count": len(all_writes),
    }


def _deduplicate_writes(writes: list[PlannedWrite]) -> list[PlannedWrite]:
    unique: list[PlannedWrite] = []
    by_destination: dict[Path, PlannedWrite] = {}
    for write in writes:
        existing = by_destination.get(write.destination)
        if existing is None:
            by_destination[write.destination] = write
            unique.append(write)
            continue
        if existing.content != write.content:
            raise RuntimeAssetInstallError(
                f"Conflicting generated runtime asset content for {write.destination}"
            )
    return unique


def _resolve_source_repo(*, repo_workdir: str | Path | None, workspace: Path) -> Path:
    try:
        repo = resolve_repo_workdir(repo_workdir, workspace=workspace)
    except ValueError as exc:
        raise RuntimeAssetInstallError(SOURCE_CLONE_ONLY_MESSAGE) from exc
    if not is_source_repo(repo):
        raise RuntimeAssetInstallError(SOURCE_CLONE_ONLY_MESSAGE)
    required = [repo / ".agents" / "skills", repo / ".opencode", repo / ".claude", repo / ".codex"]
    missing = [str(path) for path in required if not path.exists()]
    if missing:
        raise RuntimeAssetInstallError(
            f"{SOURCE_CLONE_ONLY_MESSAGE} Missing source assets: {', '.join(missing)}"
        )
    return repo


def _opencode_writes(*, workspace: Path, repo: Path) -> list[PlannedWrite]:
    return _runtime_writes(
        workspace=workspace,
        repo=repo,
        runtime="opencode",
        runtime_label="OpenCode",
        instruction_file="AGENTS.md",
    )


def _claude_writes(*, workspace: Path, repo: Path) -> list[PlannedWrite]:
    return _runtime_writes(
        workspace=workspace,
        repo=repo,
        runtime="claude",
        runtime_label="Claude Code",
        instruction_file="CLAUDE.md",
    )


def _codex_writes(*, workspace: Path, repo: Path) -> list[PlannedWrite]:
    writes: list[PlannedWrite] = [
        PlannedWrite(
            workspace / "AGENTS.md",
            _workspace_agents_text(),
        ),
        PlannedWrite(
            workspace / ".codex" / "config.toml",
            _marked_toml_source_text(repo / ".codex" / "config.toml"),
        ),
        PlannedWrite(
            workspace / ".codex" / "skills" / SKILL_NAME / "SKILL.md",
            _workspace_skill_text(runtime="Codex"),
        ),
    ]
    writes.extend(
        PlannedWrite(
            workspace / ".codex" / "agents" / src.name,
            _marked_toml_source_text(src),
        )
        for src in sorted((repo / ".codex" / "agents").glob("*.toml"))
    )
    writes.extend(
        _reference_writes(
            workspace / ".codex" / "skills" / SKILL_NAME / "references"
        )
    )
    return writes


def _runtime_writes(
    *,
    workspace: Path,
    repo: Path,
    runtime: str,
    runtime_label: str,
    instruction_file: str,
) -> list[PlannedWrite]:
    runtime_dir_name = f".{runtime}"
    writes: list[PlannedWrite] = [
        PlannedWrite(
            workspace / instruction_file,
            _workspace_agents_text(),
        ),
        PlannedWrite(
            workspace / runtime_dir_name / "skills" / SKILL_NAME / "SKILL.md",
            _workspace_skill_text(runtime=runtime_label),
        ),
    ]
    if runtime == "opencode":
        writes.insert(
            1, PlannedWrite(workspace / "opencode.jsonc", _opencode_jsonc_text())
        )
    writes.extend(
        _command_writes(
            workspace_command_dir=workspace / runtime_dir_name / "commands",
            repo_command_dir=repo / runtime_dir_name / "commands",
            runtime=runtime,
        )
    )
    writes.extend(
        PlannedWrite(
            workspace / runtime_dir_name / "agents" / src.name, _marked_source_text(src)
        )
        for src in sorted((repo / runtime_dir_name / "agents").glob("*.md"))
    )
    writes.extend(
        _reference_writes(
            workspace / runtime_dir_name / "skills" / SKILL_NAME / "references"
        )
    )
    return writes


def _reference_writes(reference_dir: Path) -> list[PlannedWrite]:
    references = {
        "runtime-workflow.md": _runtime_workflow_reference(),
        "control-surfaces.md": _control_surfaces_reference(),
        "artifact-boundary.md": _artifact_boundary_reference(),
    }
    return [
        PlannedWrite(reference_dir / name, _with_install_marker(text))
        for name, text in references.items()
    ]


def _command_writes(
    *, workspace_command_dir: Path, repo_command_dir: Path, runtime: str
) -> list[PlannedWrite]:
    writes: list[PlannedWrite] = []
    for src in sorted(repo_command_dir.glob("*.md")):
        content = (
            _workspace_command_text(runtime=runtime)
            if src.name == "generate-brief.md"
            else _marked_source_text(src)
        )
        writes.append(PlannedWrite(workspace_command_dir / src.name, content))
    return writes


def _marked_source_text(path: Path) -> str:
    return _with_install_marker(path.read_text(encoding="utf-8"))


def _marked_toml_source_text(path: Path) -> str:
    return f"{TOML_INSTALL_MARKER}\n{path.read_text(encoding='utf-8')}"


def _with_install_marker(text: str) -> str:
    """Insert the marker without breaking Markdown YAML frontmatter."""
    if text.startswith("---\n"):
        close = text.find("\n---", 4)
        if close != -1:
            close_end = close + len("\n---")
            if close_end < len(text) and text[close_end] == "\n":
                close_end += 1
            return f"{text[:close_end]}{INSTALL_MARKER}\n{text[close_end:]}"
    return f"{INSTALL_MARKER}\n{text}"


def _workspace_command_text(*, runtime: str) -> str:
    runtime_label = "OpenCode" if runtime == "opencode" else "Claude Code"
    frontmatter = (
        "---\n"
        "description: Generate a real source-grounded brief from this workspace\n"
    )
    if runtime == "opencode":
        frontmatter += "agent: brief-orchestrator\nsubtask: false\n"
    else:
        frontmatter += 'argument-hint: "[workspace-path]"\n'
    frontmatter += "---\n"
    return _with_install_marker(f"""{frontmatter}

You are the Orchestrator main agent for this MABW workspace.

Use the current project root as the workspace when no explicit path is provided.
If a workspace path is provided, use that path instead.

First create or refresh the runtime handoff/control context:

```bash
multi-agent-brief run --workspace <workspace> --runtime {runtime} --skip-doctor
```

Then read:

- `output/intermediate/agent_handoff.md`
- `output/intermediate/agent_handoff.json`
- `output/intermediate/workflow_state.json`
- `output/intermediate/artifact_registry.json`
- `output/intermediate/audience_profile_snapshot.md`
- `output/intermediate/orchestrator_control_switchboard.json`

Read contract references from `agent_handoff.json`. Do not assume this workspace
contains the MABW source repository or `configs/` directory.

Use the installed {runtime_label} project agents/subagents when available. Keep
Python as tools, validators, audit helpers, and renderers; Python is not the
brief-generation runtime.

Selection is not execution. If you enable a control with
`multi-agent-brief controls select`, explicitly run the corresponding command
afterward when appropriate.

Before finalize, run gates/state review:

```bash
multi-agent-brief gates check --workspace <workspace>
multi-agent-brief state check --workspace <workspace> --strict
```

Only finalize after audit, gates, and state review pass:

```bash
multi-agent-brief finalize --config <workspace>/config.yaml
```
""")


def _workspace_skill_text(*, runtime: str) -> str:
    codex_protocol = ""
    if runtime == "Codex":
        codex_protocol = """
Codex writer flow:

- When asked to inspect a folder, produce a Workspace Card before taking action:
  MABW config, Codex runtime kit, trust, input sources, demo-looking files,
  existing output/control state, workflow_state, and recommended next action.
- Do not launch the interactive terminal onboarding wizard inside Codex chat.
  Collect onboarding fields in one batch, write onboarding.json, show the values,
  then run `multi-agent-brief init --from-onboarding`.
- Before initializing into an existing directory, check for
  `output/intermediate/runtime_manifest.json`, `workflow_state.json`,
  `artifact_registry.json`, `event_log.jsonl`, and `output/runs/`. If present,
  ask whether to create a new workspace, overwrite config only, or reset old
  output/control state before running.
- After init or config inspection, show a Source Mode Card: manual local files,
  runtime WebSearch, external API search, source file count, and demo-looking
  source files.
- During production runs, report progress after every successful
  `state stage-complete` transaction.
"""
    return _with_install_marker(f"""---
name: multi-agent-brief-workflow
description: Workspace-local MABW runtime contract for {runtime}.
---

# Multi-Agent Brief Workflow Workspace Runtime Kit

This skill is installed into the business workspace so the runtime can operate
without reading the MABW source repository.

Start by running `multi-agent-brief run --workspace <workspace> --skip-doctor`,
then read the handoff files under `output/intermediate/`.

References:

- `references/runtime-workflow.md`
- `references/control-surfaces.md`
- `references/artifact-boundary.md`
{codex_protocol}
""")


def _workspace_agents_text() -> str:
    return f"""{INSTALL_MARKER}
# MABW Workspace Runtime Instructions

This workspace has a local MABW runtime kit installed.

Use `multi-agent-brief run --workspace . --runtime <runtime> --skip-doctor` to
create handoff and control files before delegating role work.

Do not read the MABW source repository during normal runtime execution. Read
workspace-local handoff files and project agents/skills instead.
Do not assume this workspace contains the MABW source repository or `configs/`
directory.

Python remains the setup, validation, audit, control, and rendering layer. The
external runtime Orchestrator coordinates specialist roles.

Runtime-specific assets live under `.opencode/`, `.claude/`, or `.codex/`.
"""


def _opencode_jsonc_text() -> str:
    return f"""{JSONC_INSTALL_MARKER}
{{
  // Workspace-local MABW runtime kit.
  // Agents live under .opencode/agents and commands under .opencode/commands.
  // No default_agent is forced; select brief-orchestrator explicitly if desired.
}}
"""


def _runtime_workflow_reference() -> str:
    return """# Runtime Workflow

Use `multi-agent-brief run --workspace <workspace>` as the handoff launcher.
The Orchestrator reads handoff/control files and delegates external roles:
scout, screener, claim-ledger, analyst, editor, auditor, and formatter.

The compact workflow may assign multiple stages to one runtime agent, but the
same accountable artifacts remain required.
"""


def _control_surfaces_reference() -> str:
    return """# Control Surfaces

Runtime state, feedback, quality gates, provenance projection, audience
snapshot, and control switchboard are control/context surfaces. They are not
source evidence and are not Python-executed agent stages.

Control selection records intent only. Execute selected controls explicitly.
"""


def _artifact_boundary_reference() -> str:
    return """# Artifact Boundary

Do not treat `audience_profile.md`, feedback, instructions, context documents,
or runtime control files as factual evidence.

Claim Ledger remains the source-grounded factual substrate. Final reader output
must not expose internal claim IDs, source IDs, evidence text, local paths, or
`file://` URLs.
"""
