#!/usr/bin/env python3
"""Generate platform-specific agent configurations from configs/agent_roles.yaml.

Usage:
    python scripts/generate_agent_configs.py --write
    python scripts/generate_agent_configs.py --check
    python scripts/generate_agent_configs.py --target codex
    python scripts/generate_agent_configs.py --target claude
    python scripts/generate_agent_configs.py --target skills
    python scripts/generate_agent_configs.py --target docs
"""
from __future__ import annotations

import argparse
import hashlib
import sys
import textwrap
from pathlib import Path
from typing import Any

try:
    import yaml
except ModuleNotFoundError:
    yaml = None  # type: ignore[assignment]

ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = ROOT / "configs" / "agent_roles.yaml"

AUTOGEN_HEADER_MD = "<!-- AUTO-GENERATED by scripts/generate_agent_configs.py. Edit configs/agent_roles.yaml instead. -->"
AUTOGEN_HEADER_TOML = "# AUTO-GENERATED by scripts/generate_agent_configs.py. Edit configs/agent_roles.yaml instead."

PIPELINE_TEXT = "Scout -> Screener -> Claim Ledger -> Analyst -> Editor -> Auditor -> Formatter"
HARNESS_TEXT = "draft facts pass -> final text quality pass -> rendered document quality pass -> delivery allowed"

SENSITIVE_PATTERNS = [
    "api_key", "password",
]

SENSITIVE_CONTEXT_PATTERNS = [
    "credential", "token", "webhook", "private path", "customer name",
    "internal report", "secret",
]

# Lines containing these guardrail phrases are allowed to mention sensitive words
SENSITIVE_EXEMPTIONS = [
    "do not commit", "do not store", "do not expose", "do not put",
    "do not place", "do not import", "do not migrate", "do not copy",
    "do not save", "do not include", "do not provide",
]


# ---------------------------------------------------------------------------
# Manifest I/O
# ---------------------------------------------------------------------------

def load_manifest(path: Path = MANIFEST_PATH) -> dict[str, Any]:
    if yaml is None:
        raise RuntimeError("PyYAML is required. Install with: pip install pyyaml")
    text = path.read_text(encoding="utf-8")
    data = yaml.safe_load(text)
    if not isinstance(data, dict):
        raise ValueError(f"Manifest must be a YAML mapping: {path}")
    return data


def validate_manifest(manifest: dict[str, Any]) -> None:
    required_top = ["schema_version", "project", "tool_profiles", "roles"]
    for key in required_top:
        if key not in manifest:
            raise ValueError(f"Manifest missing top-level key: {key}")

    project = manifest["project"]
    pipeline = project.get("pipeline", [])
    expected_pipeline = ["scout", "screener", "claim-ledger", "analyst", "editor", "auditor", "formatter"]
    if pipeline != expected_pipeline:
        raise ValueError(f"Subagent workflow mismatch: got {pipeline}, expected {expected_pipeline}")

    roles = manifest["roles"]
    required_fields = ["stage", "tool_profile", "description", "trigger", "responsibilities", "hard_rules"]
    for name, role in roles.items():
        for field in required_fields:
            if field not in role:
                raise ValueError(f"Role '{name}' missing field: {field}")
        tp = role["tool_profile"]
        if tp not in manifest["tool_profiles"]:
            raise ValueError(f"Role '{name}' references unknown tool_profile: {tp}")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _join_lines(items: list[str], indent: str = "- ") -> str:
    return "\n".join(f"{indent}{item}" for item in items)


def _role_tools(role: dict, profiles: dict) -> list[str]:
    tp = role["tool_profile"]
    return profiles[tp]["claude_tools"]


def _role_codex_mode(role: dict, profiles: dict) -> str:
    tp = role["tool_profile"]
    return profiles[tp]["codex_mode"]


def _sensitive_check(text: str, context: str) -> list[str]:
    """Check for actual sensitive content (not safety-rule mentions)."""
    hits = []
    for line in text.splitlines():
        lower = line.lower()
        # Skip lines that are guardrails (may mention sensitive terms)
        if any(exempt in lower for exempt in SENSITIVE_EXEMPTIONS):
            continue
        for pattern in SENSITIVE_PATTERNS + SENSITIVE_CONTEXT_PATTERNS:
            if pattern in lower:
                hits.append(f"{context}: contains '{pattern}'")
                break
    return hits


# ---------------------------------------------------------------------------
# AGENTS.md
# ---------------------------------------------------------------------------


def _render_onboarding_rules(manifest: dict) -> str:
    section = manifest.get("onboarding_rules")
    if not section:
        return ""
    title = section.get("title", "Conversational onboarding rule")
    rules = section.get("rules", [])
    lines = [f"## {title}\n", "\n"]
    for r in rules:
        lines.append(f"- {r}\n")
    return "".join(lines)


def render_agents_md(manifest: dict) -> str:
    project = manifest["project"]
    roles = manifest["roles"]
    non_goals = _join_lines(project["non_goals"])

    # Compact role summary — one line per role. Full details live in generated
    # platform-specific agent/skill files.
    role_lines = [
        f"- **{name}** ({role['stage']}): {role['description']}"
        for name, role in roles.items()
    ]
    roles_section = "\n".join(role_lines)

    context_mode_rule = (
        "## Context Mode Rule\n"
        "\n"
        "This repository has two modes:\n"
        "\n"
        "1. **Repository development mode**\n"
        "   - If the current directory contains `pyproject.toml`, `src/`, `tests/`, or `scripts/`, treat this as the source repository.\n"
        "   - In this mode, `AGENTS.md` and `CLAUDE.md` are contributor instructions for developing this tool.\n"
        "   - Debug code, edit files, and run tests normally.\n"
        "\n"
        "2. **Generated workspace mode**\n"
        "   - If the current directory contains `config.yaml`, `sources.yaml`, `user.md`, and `input/`, treat this as an end-user brief workspace.\n"
        "   - In this mode, `user.md` is user context, and `input/` contains source evidence.\n"
        "   - Repository README, examples, agent docs, and generated config files are development references rather than source evidence.\n"
        "\n"
        "Identify the active mode before running source, validation, audit, or rendering commands.\n"
    )

    return (
        f"{AUTOGEN_HEADER_MD}\n"
        f"\n"
        f"# AGENTS.md\n"
        f"\n"
        f"Python commands are support tools. The briefing runtime is the external subagent workflow:\n"
        f"\n"
        f"```text\n"
        f"{PIPELINE_TEXT}\n"
        f"```\n"
        f"\n"
        f"{context_mode_rule}\n"
        f"## Quick Start (for agents)\n"
        f"\n"
        f"Follow the single authoritative workflow below.\n"
        f"\n"
        f"### Step 1: Setup\n"
        f"\n"
        f"```bash\n"
        f"bash scripts/setup.sh\n"
        f"source .venv/bin/activate\n"
        f"```\n"
        f"\n"
        f"### Step 2: Conversational onboarding\n"
        f"\n"
        f"Ask the user about these fields in chat (accept natural-language answers):\n"
        f"\n"
        f"- Company or organization name (required)\n"
        f"- Industry or theme (required)\n"
        f"- Brief title / task objective (required)\n"
        f"- Audience (default: \"management team\")\n"
        f"- Language (default: \"English\")\n"
        f"- Cadence: daily / weekly / monthly (default: \"weekly\")\n"
        f"- Source style: official only / reliable research / broad scan (default: \"reliable research\")\n"
        f"- Output style (default: \"executive brief, conclusion-first\")\n"
        f"- Must-watch topics or entities (default: empty)\n"
        f"- Excluded sources or topics (default: empty)\n"
        f"\n"
        f"Confirm required fields and defaults explicitly. See `docs/onboarding.md` for field mappings.\n"
        f"\n"
        f"Create `onboarding.json` from the answers, then:\n"
        f"\n"
        f"```bash\n"
        f"multi-agent-brief init ../mabw-workspace --from-onboarding onboarding.json\n"
        f"```\n"
        f"\n"
        f"Use `--from-onboarding` as the workspace creation interface.\n"
        f"\n"
        f"### Step 3: Source discovery (if llm_decide)\n"
        f"\n"
        f"If `sources.yaml` has `source.mode: llm_decide`, run source discovery before invoking Scout:\n"
        f"\n"
        f"```bash\n"
        f"multi-agent-brief sources decide --config ../mabw-workspace/config.yaml\n"
        f"```\n"
        f"\n"
        f"Review `../mabw-workspace/source_candidates.yaml`, then merge approved sources:\n"
        f"\n"
        f"```bash\n"
        f"multi-agent-brief sources decide --config ../mabw-workspace/config.yaml --merge\n"
        f"```\n"
        f"\n"
        f"Local input-only mode can proceed directly to the doctor gate.\n"
        f"\n"
        f"### Step 4: Doctor\n"
        f"\n"
        f"```bash\n"
        f"multi-agent-brief doctor --config ../mabw-workspace/config.yaml\n"
        f"```\n"
        f"\n"
        f"Resolve reported configuration issues before proceeding.\n"
        f"\n"
        f"### Step 5: Scout subagent\n"
        f"\n"
        f"Use the `scout` subagent to read approved source materials, evidence inputs, and cached packages.\n"
        f"- Extract candidate reportable items.\n"
        f"- Write `output/intermediate/candidate_claims.json`.\n"
        f"\n"
        f"### Step 6: Screener subagent\n"
        f"\n"
        f"Use the `screener` subagent to dedupe, rank, freshness-check, and cap candidates.\n"
        f"- Write `output/intermediate/screened_candidates.json`.\n"
        f"\n"
        f"### Step 7: Claim Ledger subagent\n"
        f"\n"
        f"Use the `claim-ledger` subagent to convert screened candidates into source-grounded claims.\n"
        f"- Write `output/intermediate/claim_ledger.json`.\n"
        f"\n"
        f"### Step 8: Analyst subagent\n"
        f"\n"
        f"Use the `analyst` subagent to write the auditable brief from `claim_ledger.json` and `user.md`.\n"
        f"- Write in the workspace output language.\n"
        f"- Use claims in `claim_ledger.json` as the evidence base.\n"
        f"- Preserve valid `[src:CLAIM_ID]` citations.\n"
        f"- Include source dates where available.\n"
        f"- Write `output/intermediate/audited_brief.md`.\n"
        f"\n"
        f"### Step 9: Editor subagent\n"
        f"\n"
        f"Use the `editor` subagent to polish the auditable brief.\n"
        f"- Improve readability and management tone.\n"
        f"- Clean process residue and invalid citation markers.\n"
        f"- Preserve valid `[src:CLAIM_ID]` citations.\n"
        f"\n"
        f"### Step 10: Auditor subagent\n"
        f"\n"
        f"Use the `auditor` subagent to audit `output/intermediate/audited_brief.md` against `claim_ledger.json`.\n"
        f"- Check citations, support, numbers, dates, advice language, and process residue.\n"
        f"- Write or update `output/intermediate/audit_report.json`.\n"
        f"\n"
        f"### Step 11: Finalize\n"
        f"\n"
        f"```bash\n"
        f"multi-agent-brief finalize --config ../mabw-workspace/config.yaml\n"
        f"```\n"
        f"\n"
        f"This generates reader-facing `brief.md` and DOCX if configured.\n"
        f"\n"
        f"### Step 12: Report artifacts\n"
        f"\n"
        f"Summarize final artifacts, audit status, and remaining limitations.\n"
        f"\n"
        f"Use `/generate-brief <workspace>` in Claude Code for the full subagent-assisted workflow.\n"
        f"\n"
        f"---\n"
        f"\n"
        f"## Project Purpose\n"
        f"\n"
        f"This repository implements a subagent-first, source-grounded, audit-ready workflow toolkit for producing business, research, market, policy, and management briefs.\n"
        f"\n"
        f"Subagent workflow:\n"
        f"\n"
        f"```text\n"
        f"{PIPELINE_TEXT}\n"
        f"```\n"
        f"\n"
        f"## Core Principle\n"
        f"\n"
        f"Let code do lookup. Let models do judgment. Keep every important claim traceable.\n"
        f"\n"
        f"## Non-Goals\n"
        f"\n"
        f"This project is not:\n"
        f"{non_goals}\n"
        f"\n"
        f"## Development Commands\n"
        f"\n"
        f"Setup (one-time):\n"
        f"\n"
        f"```bash\n"
        f"bash scripts/setup.sh\n"
        f"source .venv/bin/activate\n"
        f"```\n"
        f"\n"
        f"Windows (PowerShell):\n"
        f"\n"
        f"```powershell\n"
        f".\\scripts\\setup.ps1\n"
        f".\\.venv\\Scripts\\Activate.ps1\n"
        f"multi-agent-brief version\n"
        f"```\n"
        f"\n"
        f"PowerShell is the Windows-native path. WSL is optional.\n"
        f"\n"
        f"Run tests:\n"
        f"\n"
        f"```bash\n"
        f"python -m pytest -q\n"
        f"```\n"
        f"\n"
        f"Run demo workspace setup:\n"
        f"\n"
        f"```bash\n"
        f"multi-agent-brief init ../mabw-workspace --demo\n"
        f"```\n"
        f"\n"
        f"Then use `/generate-brief ../mabw-workspace` in a subagent-capable runtime.\n"
        f"\n"
        f"Generate agent configs:\n"
        f"\n"
        f"```bash\n"
        f"python scripts/generate_agent_configs.py --write\n"
        f"```\n"
        f"\n"
        f"Check agent configs:\n"
        f"\n"
        f"```bash\n"
        f"python scripts/generate_agent_configs.py --check\n"
        f"```\n"
        f"\n"
        f"## Repository Guardrails\n"
        f"\n"
        f"- Keep sensitive values, private materials, and company-specific prompts out of commits.\n"
        f"- Use public or synthetic examples.\n"
        f"- Preserve Screener, Claim Ledger, and audit gates in delivery workflows.\n"
        f"- Preserve `[src:CLAIM_ID]` citations for supported statements.\n"
        f"- Keep the toolkit runnable without API keys.\n"
        f"- Run tests before completing implementation work.\n"
        f"\n"
        f"## Output Contract\n"
        f"\n"
        f"Expected artifacts:\n"
        f"\n"
        f"- `output/brief.md`\n"
        f"- `output/intermediate/audited_brief.md`\n"
        f"- `output/intermediate/claim_ledger.json`\n"
        f"- `output/intermediate/audit_report.json`\n"
        f"\n"
        f"Every important source-backed statement in `audited_brief.md` should cite a claim ID:\n"
        f"\n"
        f"```text\n"
        f"[src:CLAIM_ID]\n"
        f"```\n"
        f"\n"
        f"Every cited claim should exist in `claim_ledger.json`.\n"
        f"\n"
        f"## Harness Contract\n"
        f"\n"
        f"Harnesses own hard gates, schema checks, regression tests, CI checks, and failure conditions.\n"
        f"Prompt and skill files describe positive workflow, role boundaries, inputs, outputs, and handoffs.\n"
        f"\n"
        f"Final delivery gate:\n"
        f"\n"
        f"```text\n"
        f"{HARNESS_TEXT}\n"
        f"```\n"
        f"\n"
        f"Correct facts are necessary but not sufficient for final delivery.\n"
        f"\n"
        + _render_onboarding_rules(manifest)
        + f"\n"
        + f"## Agent Roles\n"
        f"\n"
        f"{roles_section}\n"
        f"\n"
        f"Full role details (responsibilities, guardrails, tool profiles) are in:\n"
        f"- `.claude/agents/*.md` — Claude Code subagents\n"
        f"- `.codex/agents/*.toml` — Codex custom agents\n"
        f"- `.agents/skills/*/SKILL.md` — agent skills\n"
    )


# ---------------------------------------------------------------------------
# Codex config.toml
# ---------------------------------------------------------------------------

def render_codex_config(manifest: dict) -> str:
    return textwrap.dedent(f"""\
        {AUTOGEN_HEADER_TOML}

        [agents]
        max_threads = 6
        max_depth = 1
    """)


# ---------------------------------------------------------------------------
# Codex agent TOML
# ---------------------------------------------------------------------------

def render_codex_agent(role_name: str, role: dict, manifest: dict) -> str:
    profiles = manifest["tool_profiles"]
    mode = _role_codex_mode(role, profiles)

    resp = "\n".join(f"        - {r}" for r in role["responsibilities"])
    rules = "\n".join(f"        - {r}" for r in role["hard_rules"])
    title = role_name.replace("-", " ").title()
    desc = repr(role["description"])
    trigger = role["trigger"]

    return (
        f"{AUTOGEN_HEADER_TOML}\n"
        f"\n"
        f'name = "{role_name}"\n'
        f"description = {desc}\n"
        f'developer_instructions = """\n'
        f"You are the {title} agent for multi-agent-brief-workflow.\n"
        f"\n"
        f"Subagent workflow:\n"
        f"{PIPELINE_TEXT}\n"
        f"\n"
        f"When to use:\n"
        f"{trigger}\n"
        f"\n"
        f"Responsibilities:\n"
        f"{resp}\n"
        f"\n"
        f"Guardrails:\n"
        f"{rules}\n"
        f"\n"
        f"Repository rules:\n"
        f"        - Preserve Screener, Claim Ledger, and audit gates.\n"
        f"        - Keep public examples synthetic or public-safe.\n"
        f"        - Run python -m pytest -q after behavior changes.\n"
        f"        - On Windows, use .\\scripts\\setup.ps1 and native PowerShell; WSL is optional.\n"
        f'        """\n'
    )


# ---------------------------------------------------------------------------
# Codex skill SKILL.md
# ---------------------------------------------------------------------------

def render_skill(role_name: str, role: dict, manifest: dict) -> str:
    resp = "\n".join(f"- {r}" for r in role["responsibilities"])
    rules = "\n".join(f"- {r}" for r in role["hard_rules"])
    title = role_name.replace("-", " ").title()
    desc = role["description"]
    trigger = role["trigger"]
    stage = role["stage"]
    outputs = "\n".join(f"- `{o}`" for o in manifest["project"]["output_contract"])

    return (
        f"---\n"
        f"name: {role_name}\n"
        f"description: {desc} {trigger}\n"
        f"---\n"
        f"\n"
        f"# {title} Skill\n"
        f"\n"
        f"## Purpose\n"
        f"\n"
        f"{desc}\n"
        f"\n"
        f"## When To Use\n"
        f"\n"
        f"{trigger}\n"
        f"\n"
        f"## Responsibilities\n"
        f"\n"
        f"{resp}\n"
        f"\n"
        f"## Guardrails\n"
        f"\n"
        f"{rules}\n"
        f"\n"
        f"## Subagent workflow Context\n"
        f"\n"
        f"```text\n"
        f"{PIPELINE_TEXT}\n"
        f"```\n"
        f"\n"
        f"## Expected Inputs\n"
        f"\n"
        f"Source files, claim ledger entries, or draft markdown as appropriate for the {stage} stage.\n"
        f"\n"
        f"## Expected Outputs\n"
        f"\n"
        f"Structured artifacts conforming to the workflow contract:\n"
        f"{outputs}\n"
    )


# ---------------------------------------------------------------------------
# Claude Code agent .md
# ---------------------------------------------------------------------------

def render_claude_agent(role_name: str, role: dict, manifest: dict) -> str:
    profiles = manifest["tool_profiles"]
    tools = _role_tools(role, profiles)
    tools_str = ", ".join(tools)
    title = role_name.replace("-", " ").title()
    desc = role["description"]
    trigger = role["trigger"]
    model = role.get("model", "inherit")

    resp = "\n".join(f"- {r}" for r in role["responsibilities"])
    rules = "\n".join(f"- {r}" for r in role["hard_rules"])

    return (
        f"---\n"
        f"name: {role_name}\n"
        f"description: {desc} {trigger}\n"
        f"tools: {tools_str}\n"
        f"model: {model}\n"
        f"---\n"
        f"\n"
        f"You are the {title} subagent for `multi-agent-brief-workflow`.\n"
        f"\n"
        f"Subagent workflow:\n"
        f"\n"
        f"```text\n"
        f"{PIPELINE_TEXT}\n"
        f"```\n"
        f"\n"
        f"When to use:\n"
        f"{trigger}\n"
        f"\n"
        f"Responsibilities:\n"
        f"{resp}\n"
        f"\n"
        f"Guardrails:\n"
        f"{rules}\n"
        f"\n"
        f"Repository rules:\n"
        f"- Preserve Screener, Claim Ledger, and audit gates.\n"
        f"- Keep public examples synthetic or public-safe.\n"
        f"- Run `python -m pytest -q` after behavior changes.\n"
        f"- On Windows, use `.\\scripts\\setup.ps1` in native PowerShell; WSL is optional.\n"
    )


# ---------------------------------------------------------------------------
# Docs
# ---------------------------------------------------------------------------

def render_docs(manifest: dict) -> dict[str, str]:
    roles = manifest["roles"]
    project = manifest["project"]

    # docs/agents/README.md
    role_list = "\n".join(
        f"- **{name}** ({role['stage']}): {role['description']}"
        for name, role in roles.items()
    )
    readme = textwrap.dedent(f"""\
        {AUTOGEN_HEADER_MD}

        # Agent Configuration

        This directory documents the cross-platform agent adaptation layer for `multi-agent-brief-workflow`.

        ## Source of Truth

        All agent configurations are generated from a single manifest:

        ```text
        configs/agent_roles.yaml
        ```

        Edit the manifest and regenerate to update generated files.

        ## Generation

        ```bash
        python scripts/generate_agent_configs.py --write
        python scripts/generate_agent_configs.py --check
        ```

        Windows (PowerShell):

        ```powershell
        python scripts/generate_agent_configs.py --write
        python scripts/generate_agent_configs.py --check
        ```

        ## Subagent workflow

        ```text
        {PIPELINE_TEXT}
        ```

        ## Roles

        {role_list}

        ## Platform Files

        | Platform | Location | Format |
        |----------|----------|--------|
        | Codex agents | `.codex/agents/*.toml` | TOML |
        | Codex skills | `.agents/skills/*/SKILL.md` | Markdown + YAML frontmatter |
        | Claude Code | `.claude/agents/*.md` | Markdown + YAML frontmatter |
        | OpenCode | `.opencode/agents/*.md` | Markdown + YAML frontmatter |
        | Project instructions | `AGENTS.md` | Markdown |
    """)

    # docs/agents/codex.md
    codex_roles = "\n".join(
        f"- `{name}.toml` — {role['description']}"
        for name, role in roles.items()
    )
    codex = textwrap.dedent(f"""\
        {AUTOGEN_HEADER_MD}

        # Codex Agent Configuration

        ## Custom Agents

        Located in `.codex/agents/`:

        {codex_roles}

        Each agent TOML file includes:

        - `name`
        - `description`
        - `developer_instructions`

        ## Skills

        Located in `.agents/skills/*/SKILL.md`:

        Each skill has YAML frontmatter with `name` and `description`, plus sections for purpose, responsibilities, guardrails, and expected I/O.

        ## Config

        `.codex/config.toml` sets:

        ```toml
        max_threads = 6
        max_depth = 1
        ```
    """)

    # docs/agents/claude-code.md
    claude_roles = "\n".join(
        f"- `{name}.md` — {role['description']}"
        for name, role in roles.items()
    )
    claude = textwrap.dedent(f"""\
        {AUTOGEN_HEADER_MD}

        # Claude Code Subagent Configuration

        ## Subagents

        Located in `.claude/agents/`:

        {claude_roles}

        Each subagent Markdown file has YAML frontmatter with:

        - `name`
        - `description`
        - `tools` (mapped from tool_profiles)
        - `model: inherit`

        ## Tool Profiles

        | Profile | Tools | Use |
        |---------|-------|-----|
        | read_only | Read, Grep, Glob, Bash | Scout |
        | edit_safe | Read, Grep, Glob, Bash, Edit, MultiEdit, Write | Most workflow agents |
        | audit_edit | Read, Grep, Glob, Bash, Edit, MultiEdit, Write | Audit and harness agents |

        ## Worktree Isolation

        By default, subagents share the current workspace. For risky parallel implementation tasks, users can enable worktree isolation in the agent definition or at invocation time.
    """)

    # docs/agents/opencode.md
    opencode_roles = "\n".join(
        f"- `brief-{name}.md` — {role['description']}"
        for name, role in roles.items()
    )
    opencode = textwrap.dedent(f"""\
        {AUTOGEN_HEADER_MD}

        # OpenCode Agent Configuration

        ## Agents

        Located in `.opencode/agents/` with `brief-` prefix:

        {opencode_roles}

        Each agent Markdown file has YAML frontmatter with:

        - `description`
        - `mode`: primary (brief-orchestrator) or subagent
        - `hidden`: true for workflow-internal roles
        - `permission`: mapped from tool_profiles (edit, bash, network, task)

        ## Command

        `/generate-brief` is defined in `.opencode/commands/generate-brief.md`.

        ## Generation

        ```bash
        python scripts/generate_agent_configs.py --target opencode --write
        python scripts/generate_agent_configs.py --target opencode --check
        ```
    """)

    # docs/agents/harness-subagents.md
    harness = textwrap.dedent(f"""\
        {AUTOGEN_HEADER_MD}

        # Harness Subagents

        This project has two harness layers.

        ## 1. Draft Audit Harness

        Purpose:

        ```text
        auditor subagent -> CompositeAuditAgent -> DeterministicAuditAgent -> QualityHarnessAuditAgent -> optional semantic audit adapter
        ```

        Responsible subagent:

        ```text
        draft-audit-harness
        ```

        It reviews and implements:

        * missing or orphan claim IDs
        * number/source coverage
        * reporting-window freshness
        * missing source dates
        * placeholders
        * internal workflow residue
        * process residue
        * metadata residue
        * unsupported certainty wording
        * investment-advice style language
        * needs_recrawl leakage
        * T5 or low-confidence source leakage
        * low numeric source density
        * possible unit inflation
        * repeat/background claims in executive summary
        * stale/no-update filler

        ## 2. Final Delivery Harness

        Purpose:

        ```text
        {HARNESS_TEXT}
        ```

        Responsible subagents:

        ```text
        final-quality-harness
        rendered-output-harness
        ```

        `final-quality-harness` checks:

        * final report depth
        * quiet_week handling
        * front-page metadata
        * stale-current framing
        * executive summary bullet separation
        * internal workflow residue
        * publication readiness

        `rendered-output-harness` checks:

        * DOCX/PDF rendering depth
        * heading mapping
        * bullet separation after rendering
        * footer/page fields
        * margins
        * wide table conversion
        * missing rendering dependencies

        ## Rule

        Correct facts are necessary but not sufficient for final delivery. A report can pass source audit and still be blocked by final-quality or rendered-output gates.
    """)

    # docs/agents/manifest.md
    pipeline_roles = "\n".join(
        f"- **{name}** ({role['stage']})"
        for name, role in roles.items() if role["stage"] == "pipeline"
    )
    harness_roles = "\n".join(
        f"- **{name}** ({role['stage']})"
        for name, role in roles.items() if role["stage"] == "harness"
    )
    coord_roles = "\n".join(
        f"- **{name}** ({role['stage']})"
        for name, role in roles.items() if role["stage"] == "coordination"
    )
    manifest_doc = (
        f"{AUTOGEN_HEADER_MD}\n"
        f"\n"
        f"# Agent Roles Manifest\n"
        f"\n"
        f"## Schema\n"
        f"\n"
        f"```text\n"
        f"configs/agent_roles.yaml\n"
        f"```\n"
        f"\n"
        f"Schema version: `{manifest['schema_version']}`\n"
        f"\n"
        f"## Structure\n"
        f"\n"
        f"```yaml\n"
        f'schema_version: "..."\n'
        f"project:\n"
        f'  name: "..."\n'
        f'  purpose: "..."\n'
        f"  workflow: [...]\n"
        f"  output_contract: [...]\n"
        f"  non_goals: [...]\n"
        f"tool_profiles:\n"
        f"  read_only: {{ ... }}\n"
        f"  edit_safe: {{ ... }}\n"
        f"  audit_read_only: {{ ... }}\n"
        f"  audit_edit: {{ ... }}\n"
        f"roles:\n"
        f"  <role-name>:\n"
        f"    stage: workflow | harness | coordination\n"
        f"    tool_profile: <profile-name>\n"
        f'    description: "..."\n'
        f'    trigger: "..."\n'
        f"    responsibilities: [...]\n"
        f"    hard_rules: [...]\n"
        f"```\n"
        f"\n"
        f"## Subagent workflow\n"
        f"\n"
        f"```text\n"
        f"{PIPELINE_TEXT}\n"
        f"```\n"
        f"\n"
        f"## Subagent workflow Roles\n"
        f"\n"
        f"{pipeline_roles}\n"
        f"\n"
        f"## Harness Roles\n"
        f"\n"
        f"{harness_roles}\n"
        f"\n"
        f"## Coordination Roles\n"
        f"\n"
        f"{coord_roles}\n"
    )

    return {
        "docs/agents/README.md": readme.strip() + "\n",
        "docs/agents/codex.md": codex.strip() + "\n",
        "docs/agents/claude-code.md": claude.strip() + "\n",
        "docs/agents/opencode.md": opencode.strip() + "\n",
        "docs/agents/harness-subagents.md": harness.strip() + "\n",
        "docs/agents/manifest.md": manifest_doc.strip() + "\n",
    }


def _opencode_agent_name(role_name: str) -> str:
    """Map a role name to an OpenCode-safe agent name with brief- prefix."""
    return f"brief-{role_name}"


def _opencode_visible_roles() -> set[str]:
    """Roles that are visible (not hidden) in OpenCode agent list."""
    return {
        "orchestrator",
        "source-provider",
        "source-planner",
        "analyst",
        "auditor",
        "market-competitor-planner",
        "market-competitor-analyst",
        "market-competitor-auditor",
    }


def _opencode_tool_profile_to_permission(tp: dict, role_name: str) -> dict:
    """Map a tool_profile to OpenCode permission block.

    Returns a dict suitable for YAML serialisation as the 'permission' field.
    For read-only profiles, restrict edit access. For edit profiles, allow.
    """
    may_edit = tp.get("may_edit", False)
    tools = tp.get("claude_tools", [])
    has_network = "WebFetch" in tools

    perm: dict[str, Any] = {}

    # Edit permission
    if may_edit:
        edit_allow: list[str] = []
        if role_name in ("formatter",):
            edit_allow.append("output/**")
        elif role_name in ("auditor", "draft-audit-harness", "final-quality-harness", "rendered-output-harness"):
            edit_allow.append("output/intermediate/audit_report.json")
            edit_allow.append("output/intermediate/audited_brief.md")
        elif role_name in ("source-provider", "source-planner"):
            edit_allow.append("source_candidates.yaml")
            edit_allow.append("sources.yaml")
        else:
            edit_allow.append("*")
        # Deny everything else, allow specific paths
        perm["edit"] = {"*": "deny"}
        for path in edit_allow:
            perm["edit"][path] = "allow"
    else:
        perm["edit"] = {"*": "deny"}

    # Bash permission — allow for all, but ask for read-only roles
    if may_edit:
        perm["bash"] = {"*": "allow"}
    else:
        perm["bash"] = {"*": "ask"}

    # Network — only source roles get network
    if role_name in ("source-provider", "source-planner"):
        perm["network"] = {"*": "allow"}
    else:
        perm["network"] = {"*": "deny"}

    # Task — orchestrator alone gets to invoke subagents
    if role_name == "orchestrator":
        perm["task"] = {"*": "deny", "brief-*": "allow"}
    else:
        perm["task"] = {"*": "deny"}

    return perm


def render_opencode_agent(role_name: str, role: dict, manifest: dict) -> str:
    """Render an OpenCode agent in .opencode/agents/<name>.md format."""
    profiles = manifest["tool_profiles"]
    tp = profiles[role["tool_profile"]]
    agent_name = _opencode_agent_name(role_name)

    desc = role["description"]
    trigger = role["trigger"]
    opencode_mode = "primary" if role_name == "orchestrator" else "subagent"
    hidden = role_name not in _opencode_visible_roles()

    resp = "\n".join(f"- {r}" for r in role["responsibilities"])
    rules = "\n".join(f"- {r}" for r in role["hard_rules"])

    # Build permission block
    permission = _opencode_tool_profile_to_permission(tp, role_name)
    permission_yaml = yaml.dump(permission, default_flow_style=False, sort_keys=False).strip()

    lines = ["---"]
    lines.append(f"description: {desc}")
    lines.append(f"mode: {opencode_mode}")
    if hidden:
        lines.append("hidden: true")
    lines.append("permission:")
    # Indent the permission YAML
    for perm_line in permission_yaml.splitlines():
        lines.append(f"  {perm_line}")
    lines.append("---")
    lines.append("")
    lines.append(f"You are the {desc}")
    lines.append("")
    lines.append("Subagent workflow:")
    lines.append("")
    lines.append("```text")
    lines.append(PIPELINE_TEXT)
    lines.append("```")
    lines.append("")
    lines.append("When to use:")
    lines.append(trigger)
    lines.append("")
    lines.append("Responsibilities:")
    lines.append(resp)
    lines.append("")
    lines.append("Guardrails:")
    lines.append(rules)

    return "\n".join(lines) + "\n"


def render_opencode_agents(manifest: dict) -> dict[str, str]:
    """Render all OpenCode agent files. Returns {rel_path: content}."""
    roles = manifest["roles"]
    result: dict[str, str] = {}
    for name, role in roles.items():
        rel = f".opencode/agents/{_opencode_agent_name(name)}.md"
        result[rel] = render_opencode_agent(name, role, manifest)
    return result


def render_opencode_command_generate_brief(manifest: dict) -> str:
    """Render the /generate-brief command for OpenCode."""
    _ = manifest  # used for future workflow extraction
    return (
        "---\n"
        "description: Generate a real source-grounded and audited brief\n"
        "agent: brief-orchestrator\n"
        "subtask: false\n"
        "---\n"
        "\n"
        "You are generating a real user-facing brief for workspace: $ARGUMENTS\n"
        "\n"
        "MABW uses an external subagent workflow. Python CLI commands provide setup,\n"
        "source discovery, input governance, audit checks, and final rendering tools.\n"
        "\n"
        "Follow this sequence:\n"
        "\n"
        "1. Read `$ARGUMENTS/config.yaml`, `$ARGUMENTS/sources.yaml`, `$ARGUMENTS/user.md`, and workspace inputs.\n"
        "\n"
        "2. **Source discovery gate (llm_decide only):**\n"
        "   If `sources.yaml` has `source.mode: llm_decide` and `source_candidates.yaml` "
        "does not exist or has not been merged:\n"
        "   - Run: `multi-agent-brief sources decide --config $ARGUMENTS/config.yaml`\n"
        "   - Review `$ARGUMENTS/source_candidates.yaml`.\n"
        "   - Run: `multi-agent-brief sources decide --config $ARGUMENTS/config.yaml --merge`\n"
        "\n"
        "3. **Doctor gate:**\n"
        "   - Run: `multi-agent-brief doctor --config $ARGUMENTS/config.yaml`\n"
        "   - Fix any issues before proceeding.\n"
        "\n"
        "4. **Input governance gate (if available):**\n"
        "   - Run: `multi-agent-brief inputs classify --config $ARGUMENTS/config.yaml`\n"
        "   - Pass only evidence inputs to the scout subagent.\n"
        "\n"
        "5. Invoke the **scout** subagent:\n"
        "   - Read approved source materials, evidence inputs, and cached packages.\n"
        "   - Extract candidate reportable items.\n"
        "   - Write `$ARGUMENTS/output/intermediate/candidate_claims.json`.\n"
        "\n"
        "6. Invoke the **screener** subagent:\n"
        "   - Dedupe, rank, freshness-check, and cap candidates.\n"
        "   - Write `$ARGUMENTS/output/intermediate/screened_candidates.json`.\n"
        "\n"
        "7. Invoke the **claim-ledger** subagent:\n"
        "   - Convert screened candidates into source-grounded claims.\n"
        "   - Write `$ARGUMENTS/output/intermediate/claim_ledger.json`.\n"
        "\n"
        "8. Read `$ARGUMENTS/output/intermediate/claim_ledger.json` and `$ARGUMENTS/user.md`.\n"
        "\n"
        "9. Invoke the **brief-analyst** subagent:\n"
        "   - Write the final brief from `claim_ledger.json` and `user.md`.\n"
        "   - Use only `claim_ledger.json` as source evidence.\n"
        "   - Preserve all valid [src:CLAIM_ID] citations.\n"
        "   - Write the auditable brief to `$ARGUMENTS/output/intermediate/audited_brief.md`.\n"
        "\n"
        "10. Invoke the **brief-editor** subagent:\n"
        "    - Polish for management / research team readability.\n"
        "    - Preserve valid [src:CLAIM_ID] in `audited_brief.md`.\n"
        "\n"
        "11. Invoke the **brief-auditor** subagent:\n"
        "    - Audit `$ARGUMENTS/output/intermediate/audited_brief.md` against "
        "`$ARGUMENTS/output/intermediate/claim_ledger.json`.\n"
        "\n"
        "12. **Finalize:**\n"
        "    - Run: `multi-agent-brief finalize --config $ARGUMENTS/config.yaml`\n"
        "    - Confirm `output/brief.md` strips [src:CLAIM_ID].\n"
        "\n"
        "13. **Final response:**\n"
        "    - Report artifact paths.\n"
        "    - Report audit status.\n"
        "    - Report success when audit status supports delivery.\n"
    )


def render_opencode_jsonc() -> str:
    """Render opencode.jsonc configuration for anomalyco/opencode."""
    return (
        "{\n"
        '  "$schema": "https://opencode.ai/config.json",\n'
        '  // OpenCode configuration for multi-agent-brief-workflow\n'
        '  // Generated by scripts/generate_agent_configs.py\n'
        '  // Agents are auto-discovered from .opencode/agents/\n'
        '  // Commands are auto-discovered from .opencode/commands/\n'
        "}\n"
    )

def write_or_check(path: Path, content: str, check: bool) -> bool:
    """Write content to path, or check if it matches. Returns True if OK."""
    if check:
        if not path.exists():
            try:
                label = str(path.relative_to(ROOT))
            except ValueError:
                label = str(path)
            print(f"  MISSING: {label}")
            return False
        existing = path.read_text(encoding="utf-8")
        if existing != content:
            try:
                label = str(path.relative_to(ROOT))
            except ValueError:
                label = str(path)
            print(f"  STALE: {label}")
            return False
        return True
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return True


# ---------------------------------------------------------------------------
# Main generation
# ---------------------------------------------------------------------------

def generate_all(manifest: dict, check: bool = False, target: str | None = None) -> bool:
    validate_manifest(manifest)
    roles = manifest["roles"]
    profiles = manifest["tool_profiles"]
    ok = True

    targets = {"agents_md", "codex", "claude", "skills", "docs", "opencode"} if target is None else {target}

    # AGENTS.md
    if "agents_md" in targets:
        path = ROOT / "AGENTS.md"
        content = render_agents_md(manifest)
        if not write_or_check(path, content, check):
            ok = False

    # Codex config
    if "codex" in targets:
        path = ROOT / ".codex" / "config.toml"
        content = render_codex_config(manifest)
        if not write_or_check(path, content, check):
            ok = False

        for name, role in roles.items():
            path = ROOT / ".codex" / "agents" / f"{name}.toml"
            content = render_codex_agent(name, role, manifest)
            if not write_or_check(path, content, check):
                ok = False

    # Skills
    if "skills" in targets:
        for name, role in roles.items():
            path = ROOT / ".agents" / "skills" / name / "SKILL.md"
            content = render_skill(name, role, manifest)
            if not write_or_check(path, content, check):
                ok = False

    # Claude Code
    if "claude" in targets:
        for name, role in roles.items():
            path = ROOT / ".claude" / "agents" / f"{name}.md"
            content = render_claude_agent(name, role, manifest)
            if not write_or_check(path, content, check):
                ok = False

    # Docs
    if "docs" in targets:
        docs = render_docs(manifest)
        for rel_path, content in docs.items():
            path = ROOT / rel_path
            if not write_or_check(path, content, check):
                ok = False

    # OpenCode
    if "opencode" in targets:
        agents = render_opencode_agents(manifest)
        for rel_path, content in agents.items():
            path = ROOT / rel_path
            if not write_or_check(path, content, check):
                ok = False

        cmd_path = ROOT / ".opencode" / "commands" / "generate-brief.md"
        cmd_content = render_opencode_command_generate_brief(manifest)
        if not write_or_check(cmd_path, cmd_content, check):
            ok = False

        jsonc_path = ROOT / "opencode.jsonc"
        jsonc_content = render_opencode_jsonc()
        if not write_or_check(jsonc_path, jsonc_content, check):
            ok = False

    return ok


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="generate_agent_configs",
        description="Generate platform-specific agent configs from agent_roles.yaml",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="Generate all files")
    group.add_argument("--check", action="store_true", help="Check if generated files are up to date")
    parser.add_argument("--target", choices=["codex", "claude", "skills", "docs", "agents_md", "opencode"],
                        help="Generate only a specific target")
    parser.add_argument("--manifest", type=Path, default=MANIFEST_PATH,
                        help="Path to agent_roles.yaml")

    args = parser.parse_args(argv)

    manifest = load_manifest(args.manifest)
    ok = generate_all(manifest, check=args.check, target=args.target)

    if args.check:
        if ok:
            print("All generated files are up to date.")
        else:
            print("Generated files are stale. Run: python scripts/generate_agent_configs.py --write")
        return 0 if ok else 1
    else:
        print("Generated agent configs.")
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
