# User installer for multi-agent-brief-workflow.
# Intended for:
#   irm https://raw.githubusercontent.com/Stahl-G/multi-agent-brief-workflow/main/scripts/install.ps1 | iex

[CmdletBinding()]
param(
    [string]$Prefix = $env:MABW_PREFIX,
    [string]$BinDir = $env:MABW_BIN_DIR,
    [string]$Repo = $env:MABW_REPO,
    [string]$Ref = $env:MABW_REF,
    [string]$PackageSpec = $env:MABW_PACKAGE_SPEC,
    [switch]$WithoutDocx,
    [switch]$NoPathUpdate,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

if (-not $Repo) {
    $Repo = "https://github.com/Stahl-G/multi-agent-brief-workflow"
}
if (-not $Ref) {
    $Ref = "main"
}
if (-not $Prefix) {
    $Prefix = Join-Path $env:LOCALAPPDATA "Programs\multi-agent-brief"
}
if (-not $BinDir) {
    $BinDir = Join-Path $env:LOCALAPPDATA "multi-agent-brief\bin"
}

function Write-Step {
    param([string]$Message)
    Write-Host $Message -ForegroundColor Cyan
}

function Invoke-InstallCommand {
    param(
        [Parameter(Mandatory = $true)]
        [scriptblock]$Script,
        [Parameter(Mandatory = $true)]
        [string]$Display
    )

    if ($DryRun) {
        Write-Host "+ $Display" -ForegroundColor DarkGray
    } else {
        & $Script
    }
}

function New-PythonCandidate {
    param(
        [Parameter(Mandatory = $true)]
        [string]$File,
        [string[]]$Args = @(),
        [string]$Label = ""
    )

    if (-not $Label) {
        $Label = if ($Args.Count -gt 0) { "$File $($Args -join ' ')" } else { $File }
    }
    [pscustomobject]@{
        File = $File
        Args = $Args
        Label = $Label
    }
}

function Test-PythonCandidate {
    param([Parameter(Mandatory = $true)][pscustomobject]$Candidate)

    try {
        $version = & $Candidate.File @($Candidate.Args) -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}'); raise SystemExit(0 if sys.version_info >= (3, 9) else 1)" 2>$null
        if ($LASTEXITCODE -eq 0 -and $version) {
            return $version.Trim()
        }
    } catch {
        return $null
    }
    return $null
}

function Find-Python {
    $candidates = @(
        (New-PythonCandidate -File "py" -Args @("-3") -Label "py -3"),
        (New-PythonCandidate -File "py"),
        (New-PythonCandidate -File "python"),
        (New-PythonCandidate -File "python3")
    )

    $searchPatterns = @(
        "$env:LOCALAPPDATA\Programs\Python\Python*\python.exe",
        "C:\Program Files\Python*\python.exe",
        "C:\Python*\python.exe",
        "$env:USERPROFILE\.cache\codex-runtimes\*\dependencies\python\python.exe",
        "$env:USERPROFILE\.codex\runtimes\*\python.exe"
    )

    foreach ($pattern in $searchPatterns) {
        Get-Item $pattern -ErrorAction SilentlyContinue |
            Sort-Object FullName -Descending |
            ForEach-Object {
                $candidates += New-PythonCandidate -File $_.FullName -Label $_.FullName
            }
    }

    foreach ($candidate in $candidates) {
        $version = Test-PythonCandidate -Candidate $candidate
        if ($version) {
            return [pscustomobject]@{
                Candidate = $candidate
                Version = $version
            }
        }
    }

    return $null
}

Write-Host "=== multi-agent-brief user installer ===" -ForegroundColor Cyan

$pythonInfo = Find-Python
if (-not $pythonInfo) {
    Write-Host ""
    Write-Host "ERROR: Python 3.9+ was not found." -ForegroundColor Red
    Write-Host ""
    Write-Host "Install Python, then reopen PowerShell:" -ForegroundColor Yellow
    Write-Host "  winget install Python.Python.3.12" -ForegroundColor White
    Write-Host "or download from:" -ForegroundColor Yellow
    Write-Host "  https://www.python.org/downloads/windows/" -ForegroundColor White
    exit 1
}

$python = $pythonInfo.Candidate
$repoBase = $Repo.TrimEnd("/")
if ($repoBase.EndsWith(".git")) {
    $repoBase = $repoBase.Substring(0, $repoBase.Length - 4)
}
if (-not $PackageSpec) {
    if ($env:MABW_ARCHIVE_URL) {
        $PackageSpec = $env:MABW_ARCHIVE_URL
    } else {
        $PackageSpec = "$repoBase/archive/$Ref.tar.gz"
    }
}

$venvDir = Join-Path $Prefix "venv"
$venvPython = Join-Path $venvDir "Scripts\python.exe"
$venvCli = Join-Path $venvDir "Scripts\multi-agent-brief.exe"
$shimPath = Join-Path $BinDir "multi-agent-brief.cmd"
$shimMarker = "Generated by multi-agent-brief installer."

Write-Step "[1/5] Python $($pythonInfo.Version): $($python.Label)"
Write-Step "[2/5] Install prefix: $Prefix"

Invoke-InstallCommand -Display "New-Item -ItemType Directory -Force $Prefix, $BinDir" -Script {
    New-Item -ItemType Directory -Force -Path $Prefix, $BinDir | Out-Null
}

if (-not (Test-Path $venvDir)) {
    Write-Step "[3/5] Creating virtual environment..."
    Invoke-InstallCommand -Display "$($python.Label) -m venv $venvDir" -Script {
        & $python.File @($python.Args) -m venv $venvDir
    }
} else {
    Write-Step "[3/5] Reusing virtual environment."
}

if (-not $DryRun -and -not (Test-Path $venvPython)) {
    Write-Host "ERROR: Virtual environment Python was not created at $venvPython" -ForegroundColor Red
    exit 1
}

Write-Step "[4/5] Installing multi-agent-brief from $Ref..."
Invoke-InstallCommand -Display "$venvPython -m pip install --upgrade pip -q" -Script {
    & $venvPython -m pip install --upgrade pip -q
}
if (-not $WithoutDocx) {
    Invoke-InstallCommand -Display "$venvPython -m pip install --upgrade python-docx>=1.0.0 -q" -Script {
        & $venvPython -m pip install --upgrade "python-docx>=1.0.0" -q
    }
}
Invoke-InstallCommand -Display "$venvPython -m pip install --upgrade --force-reinstall $PackageSpec -q" -Script {
    & $venvPython -m pip install --upgrade --force-reinstall $PackageSpec -q
}

Write-Step "[5/5] Creating CLI shim..."
Invoke-InstallCommand -Display "Set-Content $shimPath" -Script {
    if (Test-Path $shimPath) {
        $existing = Get-Content $shimPath -Raw -ErrorAction SilentlyContinue
        if ($existing -notlike "*$shimMarker*") {
            Write-Host "ERROR: $shimPath already exists and was not created by this installer." -ForegroundColor Red
            Write-Host "Remove it or choose a different -BinDir." -ForegroundColor Yellow
            exit 1
        }
    }

    $shim = @"
@echo off
rem $shimMarker
"$venvCli" %*
"@
    Set-Content -Path $shimPath -Value $shim -Encoding ASCII
}

if (-not $NoPathUpdate) {
    Invoke-InstallCommand -Display "Add $BinDir to user PATH if missing" -Script {
        $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
        $segments = @()
        if ($userPath) {
            $segments = $userPath -split ";" | Where-Object { $_ }
        }
        $alreadyInPath = $segments | Where-Object { $_.TrimEnd("\") -ieq $BinDir.TrimEnd("\") }
        if (-not $alreadyInPath) {
            $newPath = if ($userPath) { "$userPath;$BinDir" } else { $BinDir }
            [Environment]::SetEnvironmentVariable("Path", $newPath, "User")
            $env:Path = "$env:Path;$BinDir"
            Write-Host "Added $BinDir to your user PATH. Open a new PowerShell window if needed." -ForegroundColor Yellow
        }
    }
}

if (-not $DryRun) {
    & $venvPython -m multi_agent_brief.cli.main version | Out-Null
    & $shimPath version | Out-Null
}

Write-Host ""
Write-Host "=== Installation complete ===" -ForegroundColor Cyan
Write-Host "CLI: $shimPath"
if (-not $DryRun) {
    & $shimPath version
}
Write-Host ""
Write-Host "Next:"
Write-Host "  multi-agent-brief init my-workspace"
if ($NoPathUpdate) {
    Write-Host ""
    Write-Host "PATH was not updated. Run directly with:"
    Write-Host "  `"$shimPath`" init my-workspace"
}
